### ISSUE TITLE
Bug: tsb heap error on windows run

### ISSUE THREAD

**Issue by nasreddineskandrani** [aminpaks/typescript-library-bundler#17]
Hi,
It is a Bug Report:
Under Windows running tsb endup with a javascript heap out of memory and it seems really slow compared to MacOs.

<img width="583" alt="tsberrorheap" src="https://user-images.githubusercontent.com/1953635/34058583-86433064-e1a9-11e7-9990-2f8f656e05e7.png">

**Comment by aminpaks** [comment]
I'm gonna need some windows machine testers to help me to make sure everything is working as expected. Otherwise it's gonna be difficult me to maintain the windows compatibility.

**Comment by aminpaks** [comment]
I'm gonna update the readme to explain step by step how to debug in Windows machine.  
Give it a try and let's see what's the issue.

I will give it a shot too when I get a chance soon hopefully.

**Comment by nasreddineskandrani** [comment]
thanks @aminpaks
